print("*"*50)
file=open("tops1.txt","w")
file.write("This is file mananagemet demo using.")
file.close()
print("File written successfully")
print("*"*50)

file=open("tops1.txt","r")
print(file.read())
file.close()
print("*"*50)

file=open("tops1.txt","a")
file.write("\nThis is file is mow appended.")
file.close()
print("*"*50)

file=open("tops1.txt","r")
print(file.read())
file.close()
print("*"*50)

file=open("tops1.txt","w+")
file.write("This is w+ mode using python.")
print("Current Cursor Position : ",file.tell())
file.seek(0)
print("Fill Data : ",file.read())
file.close()
print("*"*50)
